### ISSUE TITLE
GlideApp

### ISSUE THREAD

**Issue by SirJackSparow** [ResoCoder/firebase-firestore-chat-app#3]
hello i have problem not found GlideApp

**Comment by amonkhepri** [comment]
replace Glide Gradle part with:
    //glide
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'
    kapt 'com.github.bumptech.glide:annotations:4.9.0'
 
and add 
apply plugin: 'kotlin-kapt'
on top of you gradle app file

**Comment by ghost** [comment]
You might have to also rebuild the project
